[project]
name = "roamx-trip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.1",
    "httpx>=0.28.1",
    "langchain>=1.0.1",
    "langchain-community>=0.4",
    "langchain-experimental>=0.0.42",
    "langchain-google-community[places]>=3.0.0",
    "langchain-groq>=1.0.0",
    "langchain-openai>=1.0.0",
    "langchain-tavily>=0.2.12",
    "langgraph>=1.0.1",
    "pydantic>=2.12.3",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "streamlit>=1.50.0",
    "uvicorn>=0.38.0",
]
