import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000"#Backend endpoint

#Set configuration
st.set_page_config(
    page_title="RoamX-Trip - Plan your trip",
    page_icon="🌏",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🛫 RoamX-Trip - Plan your trip")

#Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages=[]

#Display chat history
st.header("How can I help you in planning your trip? Let me know where do you want to roam around.")

#Chat input box at bottom
with st.form(key="query_form",clear_on_submit=True):
    user_input=st.text_input("User_input",placeholder="e.g. plan a trip to Thailand for 5 days.")
    submit_button=st.form_submit_button("Send")
    

if submit_button and user_input.strip():
    try:
        #Show user message
        #Show thinking spinner while backend processes
        with st.spinner("Thinking..."):
            payload = {"question":user_input}
            response = requests.post(f"{BASE_URL}/query",json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer","No answer returned.")
            markdown_content = f"""# 🌏 Travel plan with AI

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by:** RoamX-Trip agent

            ---

            {answer}

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error("Agent failed to respond: "+ response.text)

    except Exception as e:
        raise f"The response failed due to {e}"
    